"""add workspace table and workspace_id fk

Revision ID: 5303830a104c
Revises: 9fb974d519e3
Create Date: 2026-07-14 12:34:45.028880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5303830a104c'
down_revision: Union[str, Sequence[str], None] = '9fb974d519e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('source_document', sa.Column('workspace_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'source_document', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source_document', type_='foreignkey')
    op.drop_column('source_document', 'workspace_id')
    op.drop_table('workspace')
    # ### end Alembic commands ###
